#!/usr/bin/env python3
"""Convert the MSX Jawbreaker II graphics data into xas99 assembly for the TI-99/4A.

The MSX1 VDP (TMS9918A) and the TI-99/4A VDP are the same chip, so pattern,
colour and sprite data transfer byte for byte.  This script only changes the
*container*: sjasm `DB` lists and raw `incbin` blobs become xas99 `DATA` words.

Inputs  (msx/):  sprites.asm, jb2.sc2.tgp, jb2.sc2.tc, jb2-2.sc2.tgp,
                 jb2-2.sc2.tc, font.tgp
Outputs (src/):  gfx-sprites.a99, gfx-tiles.a99
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
MSX = os.path.join(ROOT, "msx")
SRC = os.path.join(ROOT, "src")

# Labels in sprites.asm that start a run of DB pattern data, in source order.
# Everything before the first one is code / sprite descriptor structures.
FIRST_DATA_LABEL = "abysslogogfx1"

LABEL_RE = re.compile(r"^([A-Za-z_][A-Za-z_0-9]*):?\s*(;.*)?$")
DB_RE = re.compile(r"^\s+(?:db|DB)\s+(.*?)\s*(?:;.*)?$")


def parse_value(tok):
    tok = tok.strip()
    if not tok:
        raise ValueError("empty value")
    if tok.endswith(("b", "B")) and set(tok[:-1]) <= set("01"):
        return int(tok[:-1], 2)
    if tok.startswith("#"):
        return int(tok[1:], 16)
    if tok.startswith("$"):
        return int(tok[1:], 16)
    return int(tok, 10) & 0xFF


def parse_sprites_asm(path):
    """Return [(label, [bytes])] for every data block, in source order."""
    blocks = []
    current = None
    started = False
    with open(path, "r", encoding="latin-1") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line.strip() or line.strip().startswith(";"):
                continue
            m = LABEL_RE.match(line)
            if m:
                name = m.group(1)
                if name == FIRST_DATA_LABEL:
                    started = True
                if started:
                    current = (name.lower(), [])
                    blocks.append(current)
                continue
            if not started:
                continue
            m = DB_RE.match(line)
            if m:
                if current is None:
                    raise SystemExit("data before first label: %r" % line)
                for tok in m.group(1).split(","):
                    current[1].append(parse_value(tok))
    return blocks


def emit_block(out, label, data, comment=None):
    if comment:
        out.write("* %s\n" % comment)
    out.write("%s\n" % label)
    # Pad odd-length blocks so that every label stays word aligned.
    if len(data) % 2:
        data = data + [0]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        words = ["".join([">%02x%02x" % (chunk[j], chunk[j + 1])])
                 for j in range(0, len(chunk), 2)]
        out.write("       data %s\n" % ",".join(words))


def convert_sprites():
    blocks = parse_sprites_asm(os.path.join(MSX, "sprites.asm"))
    total = sum(len(b[1]) for b in blocks)
    path = os.path.join(SRC, "gfx-sprites.a99")
    with open(path, "w", encoding="ascii") as out:
        out.write("* ------------------------------------------------------------------\n")
        out.write("* Sprite pattern data - generated by tools/conv_gfx.py, do not edit\n")
        out.write("* Source: msx/sprites.asm (TMS9918A data, identical on both machines)\n")
        out.write("* ------------------------------------------------------------------\n")
        for label, data in blocks:
            emit_block(out, label, data)
    return path, len(blocks), total


def convert_binaries():
    files = [
        ("jb2.sc2.tgp", "tiles_pat", "Playfield tile patterns, chars 0-31"),
        ("jb2-2.sc2.tgp", "tiles_pat2", "Title/logo tile patterns, chars 128-159"),
        ("jb2.sc2.tc", "tiles_col", "Playfield tile colours, chars 0-31"),
        ("jb2-2.sc2.tc", "tiles_col2", "Title/logo tile colours, chars 128-159"),
        ("font.tgp", "font_pat", "Font patterns, chars 32-96"),
    ]
    path = os.path.join(SRC, "gfx-tiles.a99")
    total = 0
    with open(path, "w", encoding="ascii") as out:
        out.write("* ------------------------------------------------------------------\n")
        out.write("* Tile pattern / colour data - generated by tools/conv_gfx.py\n")
        out.write("* Source: msx/*.tgp, msx/*.tc\n")
        out.write("* ------------------------------------------------------------------\n")
        for name, label, comment in files:
            with open(os.path.join(MSX, name), "rb") as f:
                data = list(f.read())
            total += len(data)
            emit_block(out, label, data, "%s (%s, %d bytes)" % (comment, name, len(data)))
    return path, total


def main():
    os.makedirs(SRC, exist_ok=True)
    p1, n, b1 = convert_sprites()
    p2, b2 = convert_binaries()
    print("%s: %d blocks, %d bytes" % (os.path.relpath(p1, ROOT), n, b1))
    print("%s: %d bytes" % (os.path.relpath(p2, ROOT), b2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
