#!/usr/bin/env python3
"""Turn the MSX ayFX bank into sound effects for the SN76489.

msx/fullsfx.afb is the bank the MSX version plays through ayFX; each
sample is a list of frames carrying a volume, and either a tone period or
a noise period.  This reads it with the format the replayer in
the MSX version's ayFX replayer (ayFX-ROM.ASM) defines and writes
src/sfx.a99 in the step format
that src/sound.a99 plays:

    sfxN   data channel            2 = tone, 3 = noise
           data value              tone divider, or noise mode
           byte attenuation,frames
           ...
           data 0

Tone periods carry over unchanged, the same way they do for the music:
the MSX AY at 1.7897725 MHz divided by 16 and the SN76489 at 3.579545 MHz
divided by 32 give the same pitch for the same number.  Frame counts are
stretched by 6/5 because the MSX plays effects at 50 Hz and the TI runs
at 60, so an effect lasts as long as it does on the MSX.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from conv_music import AY2SN, sn_tone as _sn_tone          # noqa: E402

AY_CLOCK = 1789772.5
SN_CLOCK = 3579545.0

NAMES = ["dot", "energizer", "monster", "death", "level end", "level start",
         "timer", "move", "brush", "bonus"]


def noise_rate(period):
    """AY noise period to the nearest SN76489 noise rate, white noise."""
    if period < 1:
        period = 1
    freq = AY_CLOCK / (16.0 * period)
    best, bestd = 0, None
    for rate, div in enumerate((512.0, 1024.0, 2048.0)):
        d = abs(SN_CLOCK / div - freq)
        if bestd is None or d < bestd:
            best, bestd = rate, d
    return 4 | best                                 # feedback bit = white


def sn_tone(period):
    return _sn_tone(period)[0]


def decode(bank, index):
    """One ayFX sample as a list of (volume, tone, noise, tone_on, noise_on)."""
    off = 1 + 2 * index
    ptr = off + (bank[off] | (bank[off + 1] << 8))
    frames = []
    tone = noise = 0
    while ptr < len(bank):
        c = bank[ptr]
        ptr += 1
        if c & 0x20:
            tone = bank[ptr] | (bank[ptr + 1] << 8)
            ptr += 2
        if c & 0x40:
            nz = bank[ptr]
            ptr += 1
            if nz == 0x20:                          # end of stream marker
                break
            noise = nz
        frames.append((c & 15, tone, noise, 0 if c & 0x10 else 1,
                       0 if c & 0x80 else 1))
    return frames


def convert(frames):
    """Frames to (channel, steps), each step (value, attenuation, count)."""
    # Only frames that actually sound count, and a sample can have both
    # bits set on a frame or two, so go with whichever is used more; the
    # leading frame carries volume 0 with every mask bit clear.
    sounding = [f for f in frames if f[0]]
    noisy = sum(1 for f in sounding if f[4])
    tonal = sum(1 for f in sounding if f[3])
    uses_noise = noisy > tonal
    channel = 3 if uses_noise else 2
    steps = []
    carry = 0.0
    for vol, tone, noise, tone_on, noise_on in frames:
        if channel == 3:
            value = noise_rate(noise) if noise_on else 0
        else:
            value = sn_tone(tone) if tone_on else 0
        att = AY2SN[vol] if (tone_on or noise_on) else 15
        if vol == 0:
            att = 15
        # 50 Hz to 60 Hz, keeping the fraction so the length stays right
        carry += 1.2
        n = int(carry)
        carry -= n
        if steps and steps[-1][0] == value and steps[-1][1] == att:
            steps[-1][2] += n
        else:
            steps.append([value, att, n])
    for s in steps:                                 # duration is one byte
        s[2] = max(1, min(255, s[2]))
    return channel, steps


def main():
    bank = open(os.path.join(ROOT, "msx", "fullsfx.afb"), "rb").read()
    n = bank[0] or 256
    out = [
        "* ------------------------------------------------------------------",
        "* Sound effects - generated by tools/conv_sfx.py, do not edit",
        "* Source: msx/fullsfx.afb, the ayFX bank the MSX version plays",
        "* ------------------------------------------------------------------",
    ]
    total = 0
    for i in range(n):
        frames = decode(bank, i)
        channel, steps = convert(frames)
        name = NAMES[i] if i < len(NAMES) else str(i)
        out.append("*")
        out.append("* %s: %d frames, %d steps, %s"
                   % (name, len(frames), len(steps),
                      "noise" if channel == 3 else "tone"))
        out.append("*")
        out.append("sfx%-3d data %d" % (i, channel))
        for value, att, dur in steps:
            out.append("       data %d" % value)
            out.append("       byte %d,%d" % (att, dur))
        out.append("       data 0")
        total += 2 + len(steps) * 4 + 2
        print("  %-12s %2d frames -> %2d steps (%s)"
              % (name, len(frames), len(steps), "noise" if channel == 3 else "tone"))
    path = os.path.join(ROOT, "src", "sfx.a99")
    open(path, "w").write("\n".join(out) + "\n")
    print("wrote src/sfx.a99, %d bytes of effect data" % total)


if __name__ == "__main__":
    main()
